### ISSUE TITLE
Can the space interval between the directory be configured? This interval is a bit large

### ISSUE THREAD

**Issue by moatkon** [HiDeoo/starlight-theme-rapide#3]
### Is your feature request related to a problem?

![image](https://github.com/HiDeoo/starlight-theme-rapide/assets/150421704/3f02bd35-3f5f-4883-8af5-ab09d2c5205c)
Can the space interval between the directory be configured? This interval is a bit large

### Describe the solution you'd like

Can the space interval between the directory be configured? This interval is a bit large

**Comment by HiDeoo** [comment]
👋 

The spacing was deliberately set to be large in this case (totally opinionated).

If this is something you wish to change, you should be able to use [custom CSS](https://starlight.astro.build/guides/css-and-tailwind/#custom-css-styles) and override the default styles, e.g.:

```css
.sidebar div.sidebar-pane .top-level > li + li {
  margin-top: 0.5rem;
}
```
