### ISSUE TITLE
Why the color is different?

### ISSUE THREAD

**Issue by moatkon** [HiDeoo/starlight-theme-rapide#4]
### Is your feature request related to a problem?

![image](https://github.com/HiDeoo/starlight-theme-rapide/assets/150421704/12f61104-0cc3-4338-8228-801a6d9f3690)

### Describe the solution you'd like

Why the color is different?

**Comment by HiDeoo** [comment]
👋 

This color difference is part of the default Starlight behavior ([example](https://stackblitz.com/edit/github-lbbpeg?file=README.md)) which I decided to preserve in this theme.
