### ISSUE TITLE
breaks with current starlight version

### ISSUE THREAD

**Issue by o-az** [HiDeoo/starlight-theme-rapide#8]
### Describe the bug

because of [this breaking change](https://starlight.astro.build/guides/i18n/#using-ui-translations) it's currently not possible to use this beautiful theme in starlight projects that use up to date version of `@astrojs/starlight`

### To Reproduce

install the theme in an astro starlight project that uses the current (latest) version of starlight,
run dev server,
observe errors.

### Expected behavior

it should work with the up to date version and users wanting to use the theme with older starlight versions can install a specific version from the past.

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Fixed by #7, thanks for the issue and the associated PR 👍
